[project]
name = "crystal"
version = "0.1.0"
description = "2025 Crystal Ball Cup"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.1",
    "ruff>=0.12.6",
    "seaborn>=0.13.2",
    "plotly>=5.22.0",
]
