[package]
name = "output"
version = "0.0.0"
edition = "2021"

[build-dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
csv = "1.1"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0"

mylib = { path = "../lib", version = "0.0.0"}